"""schema_update

Revision ID: 3610dab2238b
Revises: a590e80783c3
Create Date: 2026-09-13 09:47:04.532790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3610dab2238b'
down_revision: Union[str, Sequence[str], None] = 'a590e80783c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('image_prompts', sa.JSON(), nullable=False))
    op.add_column('products', sa.Column('image_prompts', sa.JSON(), nullable=False))
    op.add_column('products', sa.Column('buy_now_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'buy_now_url')
    op.drop_column('products', 'image_prompts')
    op.drop_column('articles', 'image_prompts')
    # ### end Alembic commands ###
